SELFIE_CONTEST_PLAYERS = [
    'aniafx1',
    'avatarawakening',
    'beccadeals',
    'benedicamillius',
    'bien',
    'bluelightbandit',
    'bob-elr',
    'bollutech',
    'breakthrough',
    'buckydurddle',
    'carrieallen',
    'chrismiss',
    'christjan',
    'claudene',
    'craigcryptoking',
    'dadazler',
    'davedickeyyall',
    'deadgrlsuppastar',
    'dearjyoce',
    'dennisauburn',
    'dmcamera',
    'doctorcrypto',
    'drigweeu',
    'dwells',
    'ecoinstant',
    'ecoinstante',
    'elianasgarden',
    'ellicia',
    'emem',
    'enoye',
    'ewuoso',
    'fishyculture',
    'flemingfarm',
    'gabrielmatute',
    'happymoneyman',
    'herpetologyguy',
    'ir3k',
    'ironshield',
    'japhofin8or',
    'jasonmunapasee',
    'joanderit',
    'jodiegolier',
    'kadoka',
    'kubbyelizabeth',
    'leggy23',
    'litzney',
    'lixing',
    'longsilver',
    'louiscpt',
    'mah7',
    'mariannewest',
    'marlon82',
    'matthewtiii',
    'ninahaskin',
    'norwegiansteem',
    'notaxation',
    'ny-yuti',
    'oscarcc89',
    'otage',
    'pauld',
    'pegasusphysics',
    'phelimint',
    'photolander',
    'preparedwombat',
    'randomness',
    'redrica',
    'rheasunshine',
    'rheda',
    'rogvalentin',
    'samstickkz',
    'sharoonyasir',
    'shello',
    'snooway',
    'snowpea',
    'soypaezluis',
    'splendorhub',
    'stuntworksinc',
    'susieisms',
    'tattoodjay',
    'tecnosgirl',
    'thatindianlady',
    'thefamilyman',
    'tojukaka',
    'topkpop',
    'trevor.george',
    'truconspiracy',
    'vcelier',
    'wentong-syhhae',
    'xtdnrymompreneur',
    'yusrizalhasbi',
]

PAPAPEPPER_CONTEST_ENTRIES = [
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - Registration',
        'permlink': 'the-daily-steemit-selfie-challenge-an-elimination-contest-from-papa-pepper-50-sbd-starting-prize-pool',
        'challenge': 'REGISTRATION DAY',
        'description': 'We wanted to play - so registration was the first step! All you had to do to register for gameplay is to take a selfie of yourself with a piece of paper with your username on it in the photo.',
        'prize_pool': 'The current prize pool was 50 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 1',
        'permlink': 'the-daily-steemit-selfie-challenge-day-1-60-sbd-prize-pool-and-growing',
        'challenge': 'DAY 1 : PLANT',
        'description': 'For our first round, players had 24 hours to take a selfie with a plant in the photo. As long as the plant was alive, it counted.',
        'prize_pool': 'The current prize pool was 60 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 2',
        'permlink': 'the-daily-steemit-selfie-challenge-day-2-75-sbd-prize-pool-and-growing',
        'challenge': 'DAY 2 : ANIMAL',
        'description': 'For Round 2, all you had to do was take a selfie with a live animal in the photo.',
        'prize_pool': 'The current prize pool was 75 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 3',
        'permlink': 'the-daily-steemit-selfie-challenge-day-3-1oo-sbd-prize-pool-and-growing',
        'challenge': 'DAY 3 : FIRE',
        'description': 'For Round 3, all you had to do is take a selfie with some real fire in the photo. You do not have to light yourself on fire. BE SAFE!',
        'prize_pool': 'The current prize pool was 100 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 4',
        'permlink': 'the-daily-steemit-selfie-challenge-day-4-111-sbd-prize-pool-and-growing',
        'challenge': 'DAY 4 : REFLECTIONS',
        'description': 'For Round 4, all you had to do was take a selfie with a mirror or some other way of reflecting your face. It should have been obvious that it was a reflection in your selfie.',
        'prize_pool': 'The current prize pool was 111 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 5',
        'permlink': 'the-daily-steemit-selfie-challenge-day-5-125-sbd-prize-pool-and-growing',
        'challenge': 'DAY 5 : FOOD',
        'description': 'For Round 5, all you had to do was take a selfie with some food in the photo. The goal is to have real food that you can actually eat, so a giant plastic hotdog would not have worked.',
        'prize_pool': 'The current prize pool was 125 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 6',
        'permlink': 'the-daily-steemit-selfie-challenge-day-6-140-sbd-prize-pool-and-growing',
        'challenge': 'DAY 6 : SKY',
        'description': 'For Round 6, all you had to do was take a selfie with the sky in the photo. Whether it was sunny, cloudy, a sunset, or a starry night, as long as it was the sky, it qualified!',
        'prize_pool': 'The current prize pool was 140 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 7',
        'permlink': 'the-daily-steemit-selfie-challenge-day-7-150-sbd-prize-pool-and-growing',
        'challenge': 'DAY 7 : PERFECT SELFIE SMILE LIFEHACK ATTACK!',
        'description': 'For Round 7, your selfie needed to feature <a href="https://steemit.com/howto/@papa-pepper/how-to-have-a-perfect-selfie-smile" target="_blank">my Perfect Selfie Smile lifehack</a>',
        'prize_pool': 'The current prize pool was 150 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 8',
        'permlink': 'the-daily-steemit-selfie-challenge-day-8-160-sbd-prize-pool-and-growing',
        'challenge': 'DAY 8: I GOTTA HAND IT TO YOU',
        'description': 'For Round 8, you just had to have a hand in the selfie with you. As long as it was a real, live, human hand, it qualified! You could even have used your own!',
        'prize_pool': 'The current prize pool was 160 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 9',
        'permlink': 'the-daily-steemit-selfie-challenge-day-9-175-sbd-prize-pool-and-growing',
        'challenge': 'DAY 9: CUTTING IT CLOSE',
        'description': 'For Round 9, you just had to have a knife in the selfie with you.',
        'prize_pool': 'The current prize pool was 175 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 10',
        'permlink': 'the-daily-steemit-selfie-challenge-day-10-185-sbd-prize-pool-and-growing-21-hour-round',
        'challenge': 'DAY 10: WATER YOU TALKING ABOUT?',
        'description': 'For Round 10, you just had to have water in the selfie with you.',
        'prize_pool': 'The current prize pool was 185 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 11',
        'permlink': 'the-daily-steemit-selfie-challenge-day-11-200-sbd-prize-pool-and-growing',
        'challenge': 'DAY 11: VEHICLE',
        'description': 'For Round 11, you just had to have a vehicle in the selfie with you. Maybe a car, truck, van, motorcycle or a bus.',
        'prize_pool': 'The current prize pool was 200 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 12',
        'permlink': 'the-daily-steemit-selfie-challenge-day-12-215-sbd-prize-pool-and-growing',
        'challenge': 'DAY 12: THE MONEY SHOT',
        'description': 'For Round 12, you just had to have some money in the photo with you. Ideally cash or coin currency, perhaps even from your country. It was your choice, but Papa was not talking about gold or credit cards or other things like that.',
        'prize_pool': 'The current prize pool was 215 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 13',
        'permlink': 'the-daily-steemit-selfie-challenge-day-13-230-sbd-prize-pool-and-growing',
        'challenge': 'DAY 13: FOUR MORE',
        'description': 'For Round 13, you must have had four other people in your selfie. Including yourself, this meant 5 total people. Your photo shouldn’t have had three other people, or five other people.',
        'prize_pool': 'The current prize pool was 230 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 14',
        'permlink': 'the-daily-steemit-selfie-challenge-day-14-250-sbd-prize-pool-and-growing',
        'challenge': 'DAY 14 - FIRE & WATER',
        'description': 'For Round 14, you must have had both fire and water in your selfie. Contestants were encouraged to be safe, not to burn or drown, but to get both fire and water in the photo to qualify.',
        'prize_pool': 'The current prize pool was 250 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 15',
        'permlink': 'the-daily-steemit-selfie-challenge-day-15-265-sbd-prize-pool-and-growing',
        'challenge': 'DAY 15 - THE "SEAL" OF APPROVAL',
        'description': 'Has anyone ever seen a seal balance a ball on its nose? For Round 15, you must have tried to balance a ball on your nose. Contestants were encouraged to have fun, be safe, and get those balls on their noses!',
        'prize_pool': 'The current prize pool was 265 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 16',
        'permlink': 'the-daily-steemit-selfie-challenge-day-16-275-sbd-prize-pool-and-growing',
        'challenge': 'DAY 16 - LOOK WHAT I FOUND!',
        'description': 'A tiny person! The goal here was to take a photograph with someone in the background where it looks like they are a tiny person in your hand.',
        'prize_pool': 'The current prize pool was 275 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 17',
        'permlink': 'the-daily-steemit-selfie-challenge-day-17-290-sbd-prize-pool-and-growing',
        'challenge': "DAY 17 - YOU WOULDN'T LIKE ME WHEN I AM ANGRY",
        'description': 'Take an angry selfie for this day!',
        'prize_pool': 'The current prize pool was 290 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 18',
        'permlink': 'the-daily-steemit-selfie-challenge-day-18-300-sbd-prize-pool-and-growing',
        'challenge': 'DAY 18 - BUSTED!',
        'description': 'All you had to do to qualify for this round is to take a "mug shot" photo! Whether it was straight on or a sideways shot was up to contestants, (or they could do both for this round) but they had to make sure it looks like they just caught some sort of criminal!',
        'prize_pool': 'The current prize pool was 300 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 19',
        'permlink': 'the-daily-steemit-selfie-challenge-day-19-315-sbd-prize-pool-and-growing',
        'challenge': 'DAY 19 - JUGGLE',
        'description': 'All you had to do to qualify for this round was to take a selfie with three flying objects flying through the air like you were juggling.<br/>Contestants were encouraged to make sure that Papa could count all three things!',
        'prize_pool': 'The current prize pool was 315 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 20',
        'permlink': 'the-daily-steemit-selfie-challenge-day-20-325-sbd-prize-pool-and-growing',
        'challenge': 'DAY 20 - BLACK EYE',
        'description': 'This one was inspired by the son of @dwells! Give yourself a black eye and take a selfie! <br/>Since you might not have had enough time before the cutoff for a bruise to form if you try to give yourself a real black eye, contestants were encouraged to fake it!',
        'prize_pool': 'The current prize pool was 325 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 21',
        'permlink': 'the-daily-steemit-selfie-challenge-day-21-340-sbd-prize-pool-and-growing',
        'challenge': 'DAY 21 - PEEKING',
        'description': 'Is it between some fingers, or around a corner? Perhaps it was from our behind a bush. Either way, they needed to be peeking in this selfie to qualify.',
        'prize_pool': 'The current prize pool was 340 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 22',
        'permlink': 'the-daily-steemit-selfie-challenge-day-22-350-sbd-prize-pool-and-growing',
        'challenge': 'DAY 22 - THIS LITTLE PIGGY',
        'description': 'To qualify for this round, we needed to show those piggy noses!',
        'prize_pool': 'The current prize pool was 350 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 23',
        'permlink': 'the-daily-steemit-selfie-challenge-day-23-365-sbd-prize-pool-and-growing-shortened-round',
        'challenge': 'DAY 23 - WATER ON THE HEAD',
        'description': 'To qualify for this round, contestants needed to show some water being dumped on your head. Papa did not care where the water cames from, it just needed to be a sort of "action shot" where we can see it running off of their heads.',
        'prize_pool': 'The current prize pool was 365 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 24',
        'permlink': 'the-daily-steemit-selfie-challenge-day-24-375-sbd-prize-pool-and-growing',
        'challenge': 'DAY 24 - TURN THE WORLD UPSIDEDOWN!',
        'description': 'To qualify for this round, your selfie had to be taken when you are upside down.',
        'prize_pool': 'The current prize pool was 375 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 25',
        'permlink': 'the-daily-steemit-selfie-challenge-day-25-385-sbd-prize-pool-and-growing',
        'challenge': 'DAY 25 - POWDER POWER!',
        'description': 'To qualify for this round, take a selfie of yourself blowing out some kind of powder!',
        'prize_pool': 'The current prize pool was 385 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 26',
        'permlink': 'the-daily-steemit-selfie-challenge-day-26-400-sbd-prize-pool-and-growing',
        'challenge': 'DAY 26 - THE FLAMINGO SHOE TELEPHONE!',
        'description': 'To qualify for this round, take a selfie of yourself doing the "Flamingo Shoe Telephone!" <br/>Shoe phone on one leg, with the lifted leg visible!',
        'prize_pool': 'The current prize pool was 400 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 27',
        'permlink': 'the-daily-steemit-selfie-challenge-day-27-415-sbd-prize-pool-and-growing',
        'challenge': 'DAY 27 - revved up like a deuce - Who is ready to get "blinded by the light?"',
        'description': 'To qualify for this round, we had to go somewhere dark and shine a light in our eyes.',
        'prize_pool': 'The current prize pool was 415 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 28',
        'permlink': 'the-daily-steemit-selfie-challenge-day-28-425-sbd-prize-pool-and-growing',
        'challenge': "DAY 28 - THREE-HEADED BEAST! - I'll give you a hint, you will need 2 more people for this one!",
        'description': 'To qualify for this round contestants had to get two people to put a head on each of their shoulders, so they would look like a three-headed selfie master! (Those without friends had 24 hours to make some!)',
        'prize_pool': 'The current prize pool was 425 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 29',
        'permlink': 'the-daily-steemit-selfie-challenge-day-29-435-sbd-prize-pool-and-growing',
        'challenge': 'DAY 29 - BACKWARDS PERFECT SMILE - A selfie from behind plus a perfect smile?',
        'description': 'To qualify for this round, contestants needed to take a selfie of the back of their heads, and have some "perfect selfie teeth" on too!',
        'prize_pool': 'The current prize pool was 435 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 30',
        'permlink': 'the-daily-steemit-selfie-challenge-day-30-444-sbd-prize-pool-and-growing-warning-short-round',
        'challenge': 'DAY 30 - YOU ARE WHAT YOU EAT LITTLE MAN! - How hungry are you?',
        'description': 'To qualify for this round, contestants need to take a selfie that shows themselves trying to eat a tiny person.',
        'prize_pool': 'The current prize pool was 444 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 31',
        'permlink': 'the-daily-steemit-selfie-challenge-day-31-450-sbd-prize-pool-and-growing',
        'challenge': 'DAY 31 - PLECOCTOMUS - DO YOU KNOW WHAT THAT FISH DOES?',
        'description': 'To qualify for this round, contestants needed to take a selfie wherethey are sucking on a pane of glass like a plecostomus.',
        'prize_pool': 'The current prize pool was 450 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 32',
        'permlink': 'the-daily-steemit-selfie-challenge-day-32-460-sbd-prize-pool-and-growing',
        'challenge': 'DAY 32 - SUSPENDERS - THE SUSPENDS IS KILLING ME!',
        'description': 'To qualify for this round, contestants needed to take a selfie where they were suspending, or dangling something in mid-air.',
        'prize_pool': 'The current prize pool was 460 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 33',
        'permlink': 'the-daily-steemit-selfie-challenge-day-33-475-sbd-prize-pool-and-growing',
        'challenge': 'DAY 33 - HAPPY CHIN FACE',
        'description': 'To qualify for this round, contestants needed to put some sort of "eyes" on their chin and make sure the little guy looked happy. By turning that camera or phone upside-down we could get a good look at that little guy (or gal.)',
        'prize_pool': 'The current prize pool was 475 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 34',
        'permlink': 'the-daily-steemit-selfie-challenge-day-34-485-sbd-prize-pool-and-growing',
        'challenge': 'DAY 34 - BED HEAD',
        'description': 'To qualify for this round, contestants needed to make themselves look like they just woke up.',
        'prize_pool': 'The current prize pool was 485 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 35',
        'permlink': 'the-daily-steemit-selfie-challenge-day-35-500-sbd-prize-pool-and-growing',
        'challenge': 'DAY 35 - FEEL THE BURN!',
        'description': 'To qualify this round, contestants needed to make it look like they were dangling someone over a flame or fire. It might have been tough, but it was the next theme!',
        'prize_pool': 'The current prize pool was 500 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 36',
        'permlink': 'the-daily-steemit-selfie-challenge-day-36-515-sbd-prize-pool-and-growing',
        'challenge': 'DAY 36 - DON’T HURT YOURSELF',
        'description': 'To qualify this round, contestants needed to make it look like they were threatening themselves in a reflection with a weapon.',
        'prize_pool': 'The current prize pool was 515 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 37',
        'permlink': 'the-daily-steemit-selfie-challenge-day-37-525-sbd-prize-pool-and-growing-shortened-round',
        'challenge': 'DAY 37 - PEOPLE, PETS, & A VEHICLE',
        'description': 'To qualify for this round, contestants needed to take a selfie with 3 other people, 2 animals and 1 vehicle. The 3 other people and the 2 animals should be on top of the vehicle.',
        'prize_pool': 'The current prize pool was 525 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 38',
        'permlink': 'the-daily-steemit-selfie-challenge-day-38-535-sbd-prize-pool-and-growing-shortened-round',
        'challenge': 'DAY 38 - THE STATUE OF LIBERTY',
        'description': 'To qualify this round, contestants needed to add some sort of spikes to their head and hold something up higher than their head.',
        'prize_pool': 'The current prize pool was 535 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 39',
        'permlink': 'the-daily-steemit-selfie-challenge-day-38-1050-sbd-prize-pool-and-growing-yes-1050-sbd',
        'challenge': 'DAY 39 - OPPOSING FORCES',
        'description': 'The goal of this round was to have people suspend themselves between two objects using opposing forces.',
        'prize_pool': 'The current prize pool was 1050 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 40',
        'permlink': 'the-daily-steemit-selfie-challenge-day-40-1065-sbd-prize-pool-and-growing',
        'challenge': 'DAY 40 - BURIED ALIVE!',
        'description': 'The goal of this round was to have people "get buried alive." It could be in the sand, in a pile a leaves, or even in some dirty laundry.',
        'prize_pool': 'The current prize pool was 1065 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 41',
        'permlink': 'the-daily-steemit-selfie-challenge-day-41-1075-sbd-prize-pool-and-growing',
        'challenge': "DAY 41 - THIS IS GETTIN' CRAZY",
        'description': 'The goal of this round was to have people do these three things.<br/>1 - Get one foot off of the ground.<br/>2 - Have some fire in the photo.<br/>3 - Blow some sort of powder out of their mouth.',
        'prize_pool': 'The current prize pool was 1075 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 42',
        'permlink': 'the-daily-steemit-selfie-challenge-day-42-1095-sbd-prize-pool-and-growing',
        'challenge': 'DAY 42 - IN THE DRINK',
        'description': 'To qualify this round, contestants needed to stick their heads under water.',
        'prize_pool': 'The current prize pool was 1095 SBD',
    },
    {
        'title': 'THE DAILY STEEMIT SELFIE CHALLENGE - DAY 43',
        'permlink': 'the-daily-steemit-selfie-challenge-day-43-1111-sbd-prize-pool-and-growing',
        'challenge': 'DAY 42 - ANONYMOUS @OTAGE & THE SNEAKY NINJA',
        'description': 'To qualify: <br> 1 - At least TWO PEOPLE needed to be in the photo. <br>2 - Competitors needed to put something RED over their nose and mouth to go "anonymous"<br>3 - Competitors needed to put on some sunglasses, or something that looks like sunglasses. <br>4 - ANOTHER person needed to be behind you, WITH a weapon of some sort. <br>5 - THE OTHER person needed some sunglasses, or something that looks like sunglasses. <br>6 - THE OTHER person needed to put something BLACK over their nose and mouth to finish the "SNEAKY NINJA" look',
        'prize_pool': 'The current prize pool was 1111 SBD',
    },
]
